'use strict';
window.AustinEvidence=(()=>{
 const sheet='https://docs.google.com/spreadsheets/d/1VIp8QVOUV9RNBvI0uwWqaYBgMxwFUgJmj9Y57ee_X0w/export?format=csv';let records=new Map(),status='Loading address evidence…';
 function csv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field='';}else field+=c;}row.push(field);if(row.some(v=>v.trim()))rows.push(row);const headers=(rows.shift()||[]).map(s=>s.replace(/^\uFEFF/,'').trim());return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||''])));}
 const urls=text=>(text.match(/https?:\/\/[^\s<>"']+/g)||[]).filter(u=>{try{return ['http:','https:'].includes(new URL(u).protocol);}catch{return false;}});
 function add(rows,source){for(const row of rows){const listingField=row['Airbnb and/or other listing URLs (one per line)']||'';const ids=[...listingField.matchAll(/(?:airbnb\.[a-z.]+\/rooms\/)(\d+)/gi)].map(m=>m[1]);const address=(row['Actual Address']||'').trim(),lngText=(row['Longitude (Use map to autofill)']||'').trim(),latText=(row['Latitude (Use map to autofill)']||'').trim(),lng=Number(lngText),lat=Number(latText);const point=lngText&&latText&&Number.isFinite(lng)&&Number.isFinite(lat)&&Math.abs(lng)<=180&&Math.abs(lat)<=90?[lng,lat]:null;if(!address&&!row['Proof URLs (one per line)'])continue;const value={address,point,proof_urls:urls(row['Proof URLs (one per line)']||''),source,status:source==='Public Google Sheet'?'submitted':'manual',timestamp:row.Timestamp,notes:row['Notes (i.e. what picture to match between the listings)']||'',license:row['Does this listing have a license?  If so, enter it here!']||'',credit:row['Credit (optional, can be private code or identifier you share later)']||'',other_notes:row['Any other notes? (please do not include personal details)']||'',attachment_urls:urls(row['Screenthots or other proof (reciepts, bookings, etc.)']||'')};for(const id of new Set(ids)){if(!records.has(id))records.set(id,[]);records.get(id).push(value);}}}
 async function refresh(){records=new Map();const results=await Promise.allSettled([['data/address_evidence.csv','Local address CSV'],[sheet,'Public Google Sheet']].map(async([url,source])=>{const response=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error(`${source}: ${response.status}`);const text=await response.text();if(text.trim().startsWith('<'))throw Error(`${source}: expected CSV`);add(csv(text),source);return source;}));status=results.map(r=>r.status==='fulfilled'?`${r.value} loaded`:`${r.reason.message} (unavailable)`).join(' · ');document.getElementById('evidenceStatus')?.replaceChildren(document.createTextNode(status));return records;}
 return {refresh,csv,add,get:id=>records.get(String(id))||[],status:()=>status,sheet};
})();
