'use strict';
window.AustinPreferences=(()=>{
  const consentKey='stvr_austin_consent',stateKey='stvr_austin_map';
  let timer;
  const cookie=key=>{const value=document.cookie.split('; ').find(v=>v.startsWith(key+'='));return value?decodeURIComponent(value.slice(key.length+1)):null;};
  const setCookie=(key,value,age=31536000)=>{document.cookie=`${key}=${encodeURIComponent(value)}; Path=/; Max-Age=${age}; SameSite=Lax${location.protocol==='https:'?'; Secure':''}`;};
  function read(){if(cookie(consentKey)!=='accepted')return null;try{return JSON.parse(cookie(stateKey)||'null');}catch{return null;}}
  function save(){if(cookie(consentKey)!=='accepted'||!window.austinMap)return;const m=window.austinMap.map,c=m.getCenter();const state={defaultsVersion:4,edgeBuffer:document.getElementById('edgeBuffer').value,excludedTypes:[...document.querySelectorAll('.property-type:not(:checked)')].map(e=>e.value),partyKeywords:[...document.querySelectorAll('.global-party-keyword:checked')].map(e=>e.value),hostSort:document.getElementById('hostSort').value,hostState:window.AustinHostState?.read(),center:[Number(c.lng.toFixed(6)),Number(c.lat.toFixed(6))],zoom:m.getZoom(),bearing:m.getBearing(),pitch:m.getPitch(),search:document.getElementById('search').value.slice(0,150),host:document.getElementById('host').value,hostSearch:document.getElementById('hostSearch').value.slice(0,150),detection:[...document.querySelectorAll('.detection:checked')].map(e=>e.value),checks:Object.fromEntries(['possibleRentals','possibleHosts','privacyRadii','outsideLicensePrivacy','matched','owners','blocks','parcels','resorts','hotels','heat','warnings','overOccupancy','excludeLarge','scopeOnly','globalPartyRequire','unrelatedOccupancy','themeToggle','singleHosts','includeHotelHosts'].map(id=>[id,document.getElementById(id).checked])),exploreOpen:!document.getElementById('controls').classList.contains('collapsed'),minOver:document.getElementById('minOver').value,filterScroll:Number(document.getElementById('filters').dataset.savedScroll||0),hostScroll:Number(document.getElementById('hostListScroll').dataset.savedScroll||0),hostsOpen:document.getElementById('hostMenu').open};setCookie(stateKey,JSON.stringify(state));}
  function schedule(){clearTimeout(timer);timer=setTimeout(save,250);}
  function restore(){const s=read();if(!s)return;const $=id=>document.getElementById(id);if(typeof s.search==='string')$('search').value=s.search;if(typeof s.host==='string')$('host').value=s.host;if(typeof s.hostSearch==='string')$('hostSearch').value=s.hostSearch;if(Array.isArray(s.detection))document.querySelectorAll('.detection').forEach(e=>e.checked=s.detection.includes(e.value));for(const [id,value] of Object.entries(s.checks||{}))if($(id)&&typeof value==='boolean')$(id).checked=value;document.body.classList.toggle('dark-mode',$('themeToggle').checked);$('controls').classList.toggle('collapsed',!s.exploreOpen);$('collapse').textContent=s.exploreOpen?'Hide':'Show';$('collapse').setAttribute('aria-expanded',String(!!s.exploreOpen));$('hostMenu').open=!!s.hostsOpen;$('minOver').value=s.minOver||1;$('edgeBuffer').value=((s.defaultsVersion||0)<3&&(Number(s.edgeBuffer)===0||(!s.defaultsVersion&&Number(s.edgeBuffer)===550)))?50:(s.edgeBuffer??50);document.querySelectorAll('.property-type').forEach(e=>e.checked=Array.isArray(s.excludedTypes)?(((s.defaultsVersion||0)<4&&hotelPropertyType(e.value)&&defaultTypeIncluded(e.value))||!s.excludedTypes.includes(e.value)):defaultTypeIncluded(e.value));document.querySelectorAll('.global-party-keyword').forEach(e=>e.checked=(s.partyKeywords||[]).includes(e.value));$('hostSort').value=s.hostSort||'total';requestAnimationFrame(()=>{$('filters').dataset.savedScroll=s.filterScroll||0;$('hostListScroll').dataset.savedScroll=s.hostScroll||0;$('filters').scrollTop=s.filterScroll||0;$('hostListScroll').scrollTop=s.hostScroll||0;});}
  function init(){const banner=document.getElementById('cookiePrompt');banner.hidden=!!cookie(consentKey);document.getElementById('acceptCookies').onclick=()=>{setCookie(consentKey,'accepted');banner.hidden=true;save();};document.getElementById('denyCookies').onclick=()=>{setCookie(consentKey,'denied');setCookie(stateKey,'',0);banner.hidden=true;};document.getElementById('cookieSettings').onclick=()=>{banner.hidden=false;};document.getElementById('hostMenu').addEventListener('toggle',schedule);window.addEventListener('pagehide',save);}
  return {read,restore,schedule,init};
})();
