'use strict';
window.AustinReporting=(()=>{
 let active=null,picking=null,map,marker,point=null,address='',keepPoint=false;
 const shards=new Map();
 const withoutAirbnb=v=>String(v??'').replace(/(?:Supplied\s+profile\s+URL\s*:\s*)?https?:\/\/(?:www\.)?airbnb\.[a-z.]+\/[^\s<>]+/gi,'').trim();
 const proofLinks=urls=>(urls||[]).filter(url=>{try{return !/(^|\.)airbnb\.[a-z.]+$/i.test(new URL(url).hostname);}catch{return false;}});
 const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function read(path){const r=await fetch(path);if(!r.ok)throw Error('Address data unavailable');const bytes=new Uint8Array(await r.arrayBuffer());const text=bytes[0]===31&&bytes[1]===139?await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text():new TextDecoder().decode(bytes);return JSON.parse(text);}
 async function addresses(query){const q=query.trim().toUpperCase();if(q.length<3)return [];const keys=/^\d/.test(q)?[q[0]]:await (await fetch('data/address_search/manifest.json')).json();const all=(await Promise.all(keys.map(k=>{if(!shards.has(k))shards.set(k,read(`data/address_search/${k}.json.gz`));return shards.get(k);}))).flat();const words=q.split(/\s+/);return all.filter(v=>words.every(w=>v.address.toUpperCase().includes(w))).slice(0,50);}
 function formUrl(listing,address,point){const url=new URL('https://docs.google.com/forms/d/e/1FAIpQLSd_9xNC1S9UghZE5ZrW4Ep0650C5M7bZAEqBkjyrIn93BCd_Q/viewform');url.search=new URLSearchParams({usp:'pp_url','entry.1013247072':listing.url,'entry.1545663527':address,'entry.997202982':String(point[0]),'entry.1827194001':String(point[1])});return url.href;}
 const rank=p=>p.match_type==='owner_name'?0:p.match_type==='owner_first_name'?1:p.match_type==='owner_nickname'?2:3;
 function sortedCandidates(items){return [...items].sort((a,b)=>rank(a)-rank(b)||(a.distance_m??Infinity)-(b.distance_m??Infinity));}
 function update(){const status=document.getElementById('reportSelection'),link=document.getElementById('reportForm');if(!status)return;status.textContent=address&&point?`${address} · ${point[0].toFixed(6)}, ${point[1].toFixed(6)}`:'Choose an address and coordinates before continuing.';link.hidden=!(address&&point);if(address&&point){const url=new URL('https://docs.google.com/forms/d/e/1FAIpQLSd_9xNC1S9UghZE5ZrW4Ep0650C5M7bZAEqBkjyrIn93BCd_Q/viewform');url.search=new URLSearchParams({usp:'pp_url','entry.1013247072':active.url,'entry.1545663527':address,'entry.997202982':String(point[0]),'entry.1827194001':String(point[1])});link.href=url.href;marker?.remove();marker=new maplibregl.Marker({color:'#7c3aed'}).setLngLat(point).addTo(map);}}
 function choose(value){address=value.address;if(!keepPoint)point=value.point;update();}
 function attach(listing,m){marker?.remove();marker=null;map=m;active=listing;picking=null;keepPoint=false;address='';point=null;const verified=listing.address_verification;
 const section=document.createElement('section');section.className='address-report';section.innerHTML=`${verified?`<div class="verified-address"><b>Address match · supplied verification</b><p>${escape(verified.address)}</p>${proofLinks(verified.proof_urls).map((url,i)=>`<a href="${escape(url)}" target="_blank" rel="noopener">Proof ${i+1} ↗</a>`).join(' · ')}<p class="note">${escape(verified.source)}. Building-level match; unit not verified.</p></div>`:''}<details id="addressReport"><summary>Report address for this listing</summary><label for="reportAddressSearch">Search parcel addresses</label><input id="reportAddressSearch" type="search" placeholder="Street number and street name"><label><input id="reportOnlyNames" type="checkbox"> Show name / nickname matches only</label><div id="reportCandidates" aria-live="polite"></div><button id="reportMoreCandidates" type="button" hidden>Show more candidates</button><label>Other matching parcel addresses</label><select id="reportAddressResults" size="4" aria-label="Address search results"></select><button id="reportPickParcel" type="button">Select a parcel on the map</button> <button id="reportPickPoint" type="button">Place a point on the map</button><p id="reportSelection" class="note"></p><a id="reportForm" hidden target="_blank" rel="noopener">Continue to prefilled address report ↗</a><p class="note">Selecting an address or parcel supplies coordinates. A placed point also requires selecting its address above. Review the prefilled form before submitting.</p></details>`;document.getElementById('detailBody').append(section);
 const reports=window.AustinEvidence?.get(listing.listing_id)||[];if(reports.length){const evidence=document.createElement('div');evidence.className='submitted-addresses';evidence.innerHTML='<b>Address reports</b>'+reports.map((r,i)=>`<div class="verified-address"><p>${escape(r.address)}</p><span class="note">${escape(r.source)} · ${escape(r.timestamp)} · submitted evidence</span><p>${proofLinks([...r.proof_urls,...r.attachment_urls]).map((url,j)=>`<a href="${escape(url)}" target="_blank" rel="noopener">Proof ${j+1} ↗</a>`).join(' · ')}</p>${withoutAirbnb(r.notes)?`<p>${escape(withoutAirbnb(r.notes))}</p>`:''}${r.license?`<p>Reported license: ${escape(r.license)}</p>`:''}${withoutAirbnb(r.credit)?`<p>Credit: ${escape(withoutAirbnb(r.credit))}</p>`:''}${withoutAirbnb(r.other_notes)?`<p>${escape(withoutAirbnb(r.other_notes))}</p>`:''}<button data-report-evidence="${i}">Use this address for report</button></div>`).join('');section.prepend(evidence);evidence.querySelectorAll('[data-report-evidence]').forEach(button=>button.onclick=()=>{const r=reports[Number(button.dataset.reportEvidence)];keepPoint=false;address=r.address;point=r.point;document.getElementById('addressReport').open=true;document.getElementById('reportAddressSearch').value=r.address;update();});}

 let candidates=[],loaded=false,limit=30;
 function renderCandidates(){const query=document.getElementById('reportAddressSearch').value.trim().toLowerCase(),only=document.getElementById('reportOnlyNames').checked;const items=candidates.filter(p=>(!only||rank(p)<3)&&(!query||query.split(/\s+/).every(word=>`${p.address} ${p.owner}`.toLowerCase().includes(word))));document.getElementById('reportCandidates').innerHTML=items.slice(0,limit).map(p=>`<div class="candidate ${rank(p)<3?'match':''} ${p.licensed_block_ids?.length?'licensed-candidate':''}"><strong>${escape(p.address||'Address unavailable')}</strong><span class="candidate-owner">${escape(p.owner||'Owner unavailable')}</span><span class="badge">${escape(p.match_type.replaceAll('_',' '))} · unverified</span><br><span class="candidate-distance">${p.distance_m==null?'Distance unknown':escape(p.distance_m)+' m to parcel boundary'}</span>${p.licensed_block_ids?.length?'<br>In licensed candidate block':''}<br>${p.address&&p.point?`<a class="report-candidate-link" href="${escape(formUrl(listing,p.address,p.point))}" target="_blank" rel="noopener">Select address & open report ↗</a>`:'Select an address and point using the controls below.'}</div>`).join('')||'<p class="note">No potential matches under this search / filter.</p>';document.getElementById('reportMoreCandidates').hidden=items.length<=limit;}
 document.getElementById('addressReport').addEventListener('toggle',async()=>{if(!document.getElementById('addressReport').open||loaded)return;loaded=true;const target=document.getElementById('reportCandidates');target.textContent='Loading potential parcel matches…';try{const data=await read(`data/candidates/${listing.listing_id}.json.gz`);if(active!==listing)return;candidates=sortedCandidates(data.candidates);renderCandidates();}catch(error){if(active===listing)target.textContent=error.message;}});
 document.getElementById('reportOnlyNames').onchange=()=>{limit=30;renderCandidates();};document.getElementById('reportMoreCandidates').onclick=()=>{limit+=30;renderCandidates();};
 let results=[],request=0;document.getElementById('reportAddressSearch').oninput=async e=>{const version=++request;limit=30;renderCandidates();try{const found=await addresses(e.target.value);if(version!==request)return;results=found;document.getElementById('reportAddressResults').innerHTML=found.map((v,i)=>`<option value="${i}">${escape(v.address)}</option>`).join('');document.getElementById('reportAddressResults').selectedIndex=-1;}catch(error){document.getElementById('reportSelection').textContent=error.message;}};
 document.getElementById('reportAddressResults').onchange=e=>{const value=results[Number(e.target.value)];if(value){choose(value);map.flyTo({center:point,zoom:18});}};
 function pick(mode){picking=mode;keepPoint=mode==='point';document.getElementById('detail').classList.add('preview-docked');map.getCanvas().style.cursor='crosshair';document.getElementById('reportSelection').textContent=mode==='parcel'?'Click inside a parcel. Zoom in to load parcel outlines.':'Click the map to place a point, then select its address.';document.getElementById('parcels').checked=true;window.austinMap.apply();}
 document.getElementById('reportPickParcel').onclick=()=>pick('parcel');document.getElementById('reportPickPoint').onclick=()=>pick('point');
 if(verified?.point){address=verified.address;point=verified.point;}update();}
 function click(event){if(!picking)return;const mode=picking;if(mode==='parcel'){const found=map.queryRenderedFeatures(event.point,{layers:['report-parcel-target']})[0];if(!found?.properties.address){document.getElementById('reportSelection').textContent='No addressed parcel here. Zoom closer or search its address.';return;}choose({address:found.properties.address,point:[event.lngLat.lng,event.lngLat.lat]});}else{point=[event.lngLat.lng,event.lngLat.lat];address='';document.getElementById('reportAddressResults').selectedIndex=-1;update();}picking=null;map.getCanvas().style.cursor='';}
 function close(){picking=null;marker?.remove();marker=null;if(map)map.getCanvas().style.cursor='';}
 return {attach,click,close,isPicking:()=>!!picking,addresses,sortedCandidates,formUrl};
})();
